### ISSUE TITLE
confusing line

### ISSUE THREAD

**Issue by Schiff-Lab** [claudiofronterre/spatstatReading#3]
In the handout for spatial stats, page 5, how are we supposed to handle the lines:
"
# Convert it to an sf object
lf_sp <- lf %>%
st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)
"
Thanks!
Steve

**Comment by claudiofronterre** [comment]
Steve,

Those lines have to be interpreted in the following way: 

1. take the `lf` object,
2. pass it to the function `st_as_sf` as its first argument
3. save the result of this operation to a new object called `lf_sp`

It is the equivalent to 
```r
lf_sp <- st_as_sf(lf, coord = c("Longitude", "Latitude"), crs = 4326)
```
The pipe operator `%>%` in R is very useful because it allows to concatenate consecutive operations while keeping a good readability of the code. 

For example, let's say that we have a variable `x` and we want to apply three functions, `fa`, `fb` and `fc` to it one after another. In R you could either use
```r
fc(fb(fa(x)))
```
or 
```r
x %>%
     fa() %>%
     fb() %>%
     fc() 
```
When you have a lot of functions with several arguments you can imagine that the first version starts to become messy. A lot of people also argue that in the first case you need to read from the innermost function to the outermost while in the second case you read the code like you do in a standard text, from left to right.

Little tip for Rstudio: you can use the CTRL + Sfit + M combination to insert the pipe operator.

I hope that the answer was useful.

**Comment by Schiff-Lab** [comment]
Dear Claudio

 

Thanks as always for such patient explanations to me. 

 

Unfortunately I might be missing something essential in my R installation – even the pipe command seems missing:

 

“

> library(readr)

> lf <- read_csv("data/lf.csv")

Parsed with column specification:

cols(

  .default = col_character(),

  Country_Code = col_double(),

  ADMIN1_CODE = col_double(),

  ADMIN1ID_GEO = col_double(),

  ADMIN2_CODE = col_double(),

  ADMIN2ID_GEO = col_double(),

  IU_ID = col_double(),

  Geo_reliability = col_double(),

  Longitude = col_double(),

  Latitude = col_double(),

  Year_start = col_double(),

  Year_end = col_double(),

  SurveyYear = col_double(),

  N_MDA = col_double(),

  Blood_volume = col_double(),

  Age_start = col_double(),

  Age_end = col_double(),

  Examined = col_double(),

  Positive = col_double(),

  Prevalence = col_double()

)

See spec(...) for full column specifications.

> lf_sp <- lf %>%

+     st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)

Error in lf %>% st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) : 

  could not find function "%>%"

> lf_sp <- st_as_sf(lf, coord = c("Longitude", "Latitude"), crs = 4326)

Error in st_as_sf(lf, coord = c("Longitude", "Latitude"), crs = 4326) : 

  could not find function "st_as_sf"

> 

“

 

I look forward to your thoughts!

 

Steve

**Comment by claudiofronterre** [comment]
Steve,

I forgot to tell you that the pipe operator is not loaded in R by default. You need to load one of the packages that contains it. One of these is the `sf` package that will also load all the functions needed to work with spatial objects. Running `library(sf)` on your console will solve the problem.

Cheers,

CF

**Comment by Schiff-Lab** [comment]
Thanks! That certainly did the trick :-)

 

Steve

**Comment by claudiofronterre** [comment]
Good, I am going to close this issue then :)
